//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeonTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Users
    {
        public aspnet_Users()
        {
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
            this.Mesajs = new HashSet<Mesaj>();
            this.Mesajs1 = new HashSet<Mesaj>();
            this.Bildirims = new HashSet<Bildirim>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual ICollection<Mesaj> Mesajs { get; set; }
        public virtual ICollection<Mesaj> Mesajs1 { get; set; }
        public virtual ICollection<Bildirim> Bildirims { get; set; }
    }
}
