//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeonTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public int MesajOturumId { get; set; }
        public System.Guid MesajAtanID { get; set; }
        public System.Guid MesajAlanID { get; set; }
        public string Baslik { get; set; }
        public string Konu { get; set; }
        public string Mesaj1 { get; set; }
        public Nullable<int> Oturum { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> OkunduMu { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual aspnet_Users aspnet_Users1 { get; set; }
    }
}
