//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeonTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriAdre
    {
        public int Id { get; set; }
        public System.Guid MusteriID { get; set; }
        public string Adres { get; set; }
        public string Adi { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public int PostaKodu { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
