//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeonTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public Musteri()
        {
            this.MusteriAdres = new HashSet<MusteriAdre>();
            this.Satis = new HashSet<Sati>();
        }
    
        public System.Guid Id { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string KullaniciAdi { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<MusteriAdre> MusteriAdres { get; set; }
        public virtual ICollection<Sati> Satis { get; set; }
    }
}
