//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeonTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sati
    {
        public Sati()
        {
            this.SatisDetays = new HashSet<SatisDetay>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> MusteriID { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public decimal ToplamTutar { get; set; }
        public bool Sepettemi { get; set; }
        public Nullable<int> KargoID { get; set; }
        public Nullable<int> SiparisDurumID { get; set; }
        public string KargoTakipNo { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual SiparisDurum SiparisDurum { get; set; }
        public virtual ICollection<SatisDetay> SatisDetays { get; set; }
    }
}
